version: '3.8'

services:
  redis:
    image: redis:6-alpine

  web:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0 
      - CELERY_RESULT_BACKEND=redis://redis:6379/0 
    depends_on:
      - redis 

  celery:
    build: . 
    command: celery -A netology_pd_diplom worker --loglevel=info
    volumes:
      - .:/app 
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis 