version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://diplom_user:password@db:5432/diplom_db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=diplom_db
      - POSTGRES_USER=diplom_user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data: